package com.realityexpander.alamohunt;

import com.google.android.gms.maps.model.Marker;

import java.io.Serializable;

/**
 * Created by CDA on 4/27/18.
 */

public class Venue implements Serializable {
    private String name;
    private String Id;
    private String categoryName;
    private Double latitude;
    private Double longitude;
    private Marker marker;


    public Venue(String name, String id, String categoryName){
        this.setName(name);
        this.setId(id);
        this.setCategoryName(categoryName);
    }

    public Venue(String name, String id, String categoryName, Double latitude, Double longitude){
        this.setName(name);
        this.setId(id);
        this.setCategoryName(categoryName);
        this.setLatitude(latitude);
        this.setLongitude(longitude);
    }

    public String getName() {
        return name;
    }
    public String getId() {
        return Id;
    }
    public String getCategoryName() {
        return categoryName;
    }
    public Double getLatitude() {return latitude;}
    public Double getLongitude() {return longitude;}
    public Marker getMarker(){return marker;}

    public void setName(String name) {
        this.name = name;
    }
    public void setId(String id) {
        this.Id = id;
    }
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public void setMarker(Marker marker) {this.marker = marker;}
}

//package com.realityexpander.alamohunt;
//
//import android.os.Parcel;
//import android.os.Parcelable;
//
///**
// * Created by CDA on 4/27/18.
// * Parcelable generated by parcelabler.com
// */
//
//public class Venue implements Parcelable {
//    private String name;
//    private String Id;
//    private String categoryName;
//    private Double latitude;
//    private Double longitude;
//
//
//    public Venue(String name, String id, String categoryName){
//        this.setName(name);
//        this.setId(id);
//        this.setCategoryName(categoryName);
//    }
//
//    public Venue(String name, String id, String categoryName, Double latitude, Double longitude){
//        this.setName(name);
//        this.setId(id);
//        this.setCategoryName(categoryName);
//        this.setLatitude(latitude);
//        this.setLongitude(longitude);
//    }
//
//    public String getName() {
//        return name;
//    }
//    public String getId() {
//        return Id;
//    }
//    public String getCategoryName() {
//        return categoryName;
//    }
//    public Double getLatitude() {return latitude;}
//    public Double getLongitude() {return longitude;}
//
//    public void setName(String name) {
//        this.name = name;
//    }
//    public void setId(String id) {
//        this.Id = id;
//    }
//    public void setCategoryName(String categoryName) {
//        this.categoryName = categoryName;
//    }
//    public void setLatitude(Double latitude) {
//        this.latitude = latitude;
//    }
//    public void setLongitude(Double longitude) {
//        this.longitude = longitude;
//    }
//
//    protected Venue(Parcel in) {
//        name = in.readString();
//        Id = in.readString();
//        categoryName = in.readString();
//        latitude = in.readByte() == 0x00 ? null : in.readDouble();
//        longitude = in.readByte() == 0x00 ? null : in.readDouble();
//    }
//
//    @Override
//    public int describeContents() {
//        return 0;
//    }
//
//    @Override
//    public void writeToParcel(Parcel dest, int flags) {
//        dest.writeString(name);
//        dest.writeString(Id);
//        dest.writeString(categoryName);
//        if (latitude == null) {
//            dest.writeByte((byte) (0x00));
//        } else {
//            dest.writeByte((byte) (0x01));
//            dest.writeDouble(latitude);
//        }
//        if (longitude == null) {
//            dest.writeByte((byte) (0x00));
//        } else {
//            dest.writeByte((byte) (0x01));
//            dest.writeDouble(longitude);
//        }
//    }
//
//    @SuppressWarnings("unused")
//    public static final Parcelable.Creator<Venue> CREATOR = new Parcelable.Creator<Venue>() {
//        @Override
//        public Venue createFromParcel(Parcel in) {
//            return new Venue(in);
//        }
//
//        @Override
//        public Venue[] newArray(int size) {
//            return new Venue[size];
//        }
//    };
//}



//// xxxxxxx